apiVersion: v2
appVersion: latest
description: askgigi is a skin of SearXNG, a free internet metasearch engine which aggregates results from various search services and databases.
name: askgigi
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - searx
  - searxng
  - search engine
  - privacy
  - askgigi
icon: https://github.com/searxng/searxng/blob/master/searx/static/themes/simple/img/favicon.png?raw=true
sources:
  - https://github.com/pgrew/askgigi
  - https://docs.searxng.org
  - https://hub.docker.com/r/searxng/searxng
maintainers:
  - name: pgrew
    email: pgrewatprotonmaildotcom
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
  - name: redis
    version: 0.0.3
    repository: https://charts.pascaliske.dev
    condition: redis.enabled
